// Get all platforms
curl -X GET http://localhost:3020/api/v1/platform \
  -H "Content-Type: application/json" \
  -H "x-wallet-access-key: f62815608e533bf9d6035fbb4b74c43df3fe441c09078d1d39be3977cf652258" \
  -H "authorization: Bearer f53684b6d28e6ed01cefeccbffa23f9e49ac3d33f5406ba342754a0816ec2bda"

###

// Create a new platform
curl -X POST http://localhost:3020/api/v1/platform \
  -H "Content-Type: application/json" \
  -d '{"name":"Reza Private Key","description":"Get wallet platform"}' \

###

// Create a new wallet
curl -X POST http://localhost:3020/api/v1/wallet \
  -H "Content-Type: application/json" \
  -H "x-wallet-access-key: 91fc53e2da69085a816fb1b0881f6aa7b622e4fd18c122b6947ccbb9f320d306" \
  -H "Authorization: Bearer 8fa1043325d1cdea0ef0b19ac289b462a65d2b12a3cc6c78188e4ab0a7297306" 

###

// Get wallet by private key
curl -X POST http://localhost:3020/api/v1/wallet/private \
  -H "Content-Type: application/json" \
  -H "x-wallet-access-key: e16c1e0cbe6c2d279bd49e000f32f3a0b540e7af16ac2a2f422539c66dab6f00" \
  -H "Authorization: Bearer 0aa2402e2ca3c09f4a77a7dd86abe8a7d7d920919c7a23e76e8c1133c54aec84" \
  -d '{
    "privateKey": "0xfe91b32115f23b060e695cc7b662d595c2ccdecdb89553a1c4a658cb8bec9873"
  }'

###

// Get wallet by mnemonic
curl -X POST http://localhost:3020/api/v1/wallet/mnemonic \
  -H "Content-Type: application/json" \
  -H "x-wallet-access-key: e16c1e0cbe6c2d279bd49e000f32f3a0b540e7af16ac2a2f422539c66dab6f00" \
  -H "Authorization: Bearer 0aa2402e2ca3c09f4a77a7dd86abe8a7d7d920919c7a23e76e8c1133c54aec84" \
  -d '{
    "mnemonic": "buddy chef two garden pelican hamster magic pyramid lake belt salad ridge"
  }'

###

// Get wallet balance
curl -X POST http://localhost:3020/api/v1/wallet/balance \
  -H "Content-Type: application/json" \
  -H "x-wallet-access-key: 91fc53e2da69085a816fb1b0881f6aa7b622e4fd18c122b6947ccbb9f320d306" \
  -H "Authorization: Bearer 8fa1043325d1cdea0ef0b19ac289b462a65d2b12a3cc6c78188e4ab0a7297306" \
  -d '{
    "address": "0xFbd97Aa68Fc37a180E8a4835424C6e6c3D224b09",
    "network": "ethereum"
  }'

###

// Convert from Fiat to ETH / Matic
curl -X POST "http://localhost:3020/api/v1/wallet/convert" \
  -H "Content-Type: application/json" \
  -H "x-wallet-access-key: 6fee883bca344c4598c3f5205c27690d4ea17b38eeee5b0207d8824b6c682db2" \
  -H "authorization: Bearer 4588d0a7f640ed52fccc1c20d9db9ba1d55fc7da755c46f9bb5a4aa972cbb79f" \
  -d '{
    "fiatCurrency": "USD",
    "cryptoSymbol": "ETH",
    "amount": 100
  }'

###

// Get transaction detail by txHash
curl -X POST http://localhost:3020/api/v1/wallet/transaction/detail \
  -H "Content-Type: application/json" \
  -H "x-wallet-access-key: 7fa91f52afb7635853680779755c4f2d40014e8f14bc1b5f08b3bf4ab1e056b0" \
  -H "Authorization: Bearer ac02294d899eafe128cc85bdb527fa87e9a0601b37134e5faefb2965de3166af" \
  -d '{
    "txHash": "0x3384291afad5486985d0d79be408b0dc1bfa6b703ae728135ff57038c524dd1d",
    "network": "polygon"
  }'

###

// Get transaction history by address
curl -X POST "http://localhost:3020/api/v1/wallet/transaction/history" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -H "x-wallet-access-key: 7fa91f52afb7635853680779755c4f2d40014e8f14bc1b5f08b3bf4ab1e056b0" \
  -H "Authorization: Bearer ac02294d899eafe128cc85bdb527fa87e9a0601b37134e5faefb2965de3166af" \
  -d '{
    "address": "0x77af86669adfab004041c8ef0aa80a68ea1770e4",
    "network": "polygon"
  }'

###

# {
#   "response": 200,
#   "message": "Transaction history fetched successfully!",
#   "data": []
# }

###

# {
#   "response": 201,
#   "message": "New wallet created successfully!",
#   "data": {
#     "address": "0xead9277CD7Bf281806155089E82391b2B56AbB7b",
#     "privateKey": "0xfe91b32115f23b060e695cc7b662d595c2ccdecdb89553a1c4a658cb8bec9873",
#     "mnemonic": "buddy chef two garden pelican hamster magic pyramid lake belt salad ridge"
#   }
# }

###

# {
#   "response": 200,
#   "message": "Wallet retrieved successfully from mnemonic!",
#   "data": {
#     "address": "0xead9277CD7Bf281806155089E82391b2B56AbB7b",
#     "privateKey": "0xfe91b32115f23b060e695cc7b662d595c2ccdecdb89553a1c4a658cb8bec9873",
#     "mnemonic": "buddy chef two garden pelican hamster magic pyramid lake belt salad ridge"
#   }
# }

###

# {
#   "response": 200,
#   "message": "Balance fetched successfully!",
#   "data": {
#     "address": "0xead9277CD7Bf281806155089E82391b2B56AbB7b",
#     "network": "ethereum",
#     "balanceWei": "0",
#     "balanceEth": "0.0"
#   }
# }

###

# {
#   "response": 200,
#   "message": "Conversion succeed!",
#   "data": {
#     "cryptoSymbol": "ETH",
#     "fiatCurrency": "USD",
#     "fiatAmount": 100,
#     "pricePerUnit": 3173.1002837338233,
#     "cryptoAmount": 0.03151491949769985
#   }
# }

###

// Transaction history
# {
#   "response": 200,
#   "message": "Transaction history fetched successfully!",
#   "data": [
#     {
#       "blockNumber": "72551865",
#       "blockHash": "0x3b95830c8752b3138142e89e720c6106acf4d6e0bd486354df6c095b6f0d36a5",
#       "timeStamp": "1749464566",
#       "hash": "0x3384291afad5486985d0d79be408b0dc1bfa6b703ae728135ff57038c524dd1d",
#       "nonce": "71049",
#       "transactionIndex": "2",
#       "from": "0x51836a753e344257b361519e948ffcaf5fb8d521",
#       "to": "0x77af86669adfab004041c8ef0aa80a68ea1770e4",
#       "value": "1000000000000000000",
#       "gas": "150000",
#       "gasPrice": "250000000000",
#       "input": "0x",
#       "methodId": "0x",
#       "functionName": "",
#       "contractAddress": "",
#       "cumulativeGasUsed": "237033",
#       "txreceipt_status": "1",
#       "gasUsed": "21000",
#       "confirmations": "6707970",
#       "isError": "0"
#     }
#   ]
# }

// Transaction detail
# {
#   "response": 200,
#   "message": "Transaction detail fetched successfully!",
#   "data": {
#     "blockHash": "0x3b95830c8752b3138142e89e720c6106acf4d6e0bd486354df6c095b6f0d36a5",
#     "blockNumber": "0x4530db9",
#     "from": "0x51836a753e344257b361519e948ffcaf5fb8d521",
#     "gas": "0x249f0",
#     "gasPrice": "0x3a35294400",
#     "hash": "0x3384291afad5486985d0d79be408b0dc1bfa6b703ae728135ff57038c524dd1d",
#     "input": "0x",
#     "nonce": "0x11589",
#     "to": "0x77af86669adfab004041c8ef0aa80a68ea1770e4",
#     "transactionIndex": "0x2",
#     "value": "0xde0b6b3a7640000",
#     "type": "0x0",
#     "chainId": "0x89",
#     "v": "0x136",
#     "r": "0xdfffac90cd500f55bbc11293e27bfc8887a05af3afdfd8a014a8b0aaa1c8499e",
#     "s": "0x26d0bd01eb94189c0d8fe05f83056f36da6081a8a5dad289bae6de0bc8a3a791"
#   }
# }